remote_theme: daviddarnes/alembic

title: Statistical Learning Seminars
description: Online seminar series on statistical learning and related topics
logo: logo.png

github:
  is_project_page: false
  is_user_page: false
