# Set theme
remote_theme: daviddarnes/alembic@main

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock
- .Rproj.user/

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site settings
url: "https://statistical-learning-seminars.github.io/"
baseurl: ''
title: Statistical Learning Seminars
description: Online seminar series on statistical learning and related topics
permalink: pretty
logo: "/assets/logo.png"
# Pagination
paginate: 5
paginate_path: blog/page:num
email: johanlarsson@outlook.com

# Header nav
navigation_header:
- title: Home
  url: /
- title: SLOPE Mini-Conference
  url: /slope-conference/
- title: Previous Talks
  url: /previous-talks/
- title: Links
  url: /links/
- title: About
  url: /about/

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "My thoughts and ideas"
    feature_text: |
      Welcome to my blog
    feature_image: ""



